version: '3.6'

services:

  medcat-1-2:
    build:
        context: ./
        dockerfile: ./docker/medcat-1-2/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cmf_medcat-1-2
    volumes:
      - ${MODEL_PACK_FULL_PATH}:/app/model/${BASE_MODEL_PACK}:ro
    environment:
      - CODE_TYPE=snomed
      - BASE_MODEL_PACK=${BASE_MODEL_PACK}
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    ports:
      - 8180:8000

  medcat-1-2-icd10:
    build:
        context: ./
        dockerfile: ./docker/medcat-1-2/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cmf_medcat-1-2-icd10
    volumes:
      - ${MODEL_PACK_FULL_PATH}:/app/model/${BASE_MODEL_PACK}:ro
    environment:
      - CODE_TYPE=icd10
      - BASE_MODEL_PACK=${BASE_MODEL_PACK}
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    ports:
      - 8181:8000