version: "3.6"

services:

  medcat-1-2:
    build:
        context: ./
        dockerfile: ./docker/medcat-1-2/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms_medcat-1-2
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
    environment:
      - CODE_TYPE=snomed
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    ports:
      - 8180:8000

  medcat-1-2-icd10:
    build:
        context: ./
        dockerfile: ./docker/medcat-1-2/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms_medcat-1-2-icd10
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
    environment:
      - CODE_TYPE=icd10
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    ports:
      - 8181:8000

  de-identification:
    build:
        context: ./
        dockerfile: ./docker/de-id/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms_medcat-de-id
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
    environment:
      - INCLUDE_ANNOTATION_TEXT=${INCLUDE_ANNOTATION_TEXT}
      - CODE_TYPE=userdefined
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    ports:
      - 8182:8000