version: "3.6"

name: cms

services:

  proxy:
    image: nginx:1.23.0
    restart: always
    networks:
      - cogstack-model-serve_cms
    volumes:
      - ./docker/nginx/etc/nginx/root-ca.pem:/etc/nginx/root-ca.pem:ro
      - ./docker/nginx/etc/nginx/root-ca.key:/etc/nginx/root-ca.key:ro
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/etc/nginx/cors.conf:/etc/nginx/cors.conf:ro
      - ./docker/nginx/etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./docker/nginx/etc/nginx/.htpasswd:/etc/nginx/.htpasswd
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=localhost
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=localhost
    expose:
      - 443
    ports:
      - 443:443     # cms
      - 28199:28199 # minio
      - 28200:28200 # mlflow-ui
      - 28201:28201 # prometheus
      - 28202:28202 # grafana
      - 28203:28203 # graylog
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 60s
      timeout: 20s
      retries: 3

networks:
  cogstack-model-serve_cms:
    external: true
