# This is for spinning up core services as single hosts in the DEV environment
version: "3.6"

services:

  medcat-snomed:
    build:
        context: ./
        dockerfile: ./docker/medcat-snomed/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms_medcat-snomed
    restart: always
    networks:
      - cms
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - retrained-models:/app/model/retrained
      - ./docker/medcat-snomed/.env:/app/envs/.env:ro
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
    expose:
      - 8000
    ports:
      - 8180:8000
    mem_limit: 30g

  medcat-icd10:
    build:
        context: ./
        dockerfile: ./docker/medcat-icd10/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms_medcat-icd10
    restart: always
    networks:
      - cms
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - retrained-models:/app/model/retrained
      - ./docker/medcat-icd10/.env:/app/envs/.env:ro
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
    expose:
      - 8000
    ports:
      - 8181:8000
    mem_limit: 30g

  de-identification:
    build:
        context: ./
        dockerfile: ./docker/de-id/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms_medcat-de-id
    restart: always
    networks:
      - cms
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - ./docker/de-id/.env:/app/envs/.env:ro
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    expose:
      - 8000
    ports:
      - 8182:8000

volumes:
  retrained-models:
    driver: local

networks:
  cms:
    driver: bridge