# This is for spinning up core services as single hosts in the DEV environment
version: "3.6"

services:

  medcat-snomed:
    build:
        context: ./
        dockerfile: ./docker/medcat-snomed/Dockerfile
        args:
          - CMS_MODEL_NAME=SNOMED MedCAT model
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms-dev_medcat-snomed
    restart: always
    networks:
      - cms-dev
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - retrained-models:/app/model/retrained
      - ./docker/medcat-snomed/.env:/app/envs/.env:ro
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
    expose:
      - 8000
    ports:
      - 8180:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s

  medcat-icd10:
    build:
        context: ./
        dockerfile: ./docker/medcat-icd10/Dockerfile
        args:
          - CMS_MODEL_NAME=ICD-10 MedCAT model
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms-dev_medcat-icd10
    restart: always
    networks:
      - cms-dev
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - retrained-models:/app/model/retrained
      - ./docker/medcat-icd10/.env:/app/envs/.env:ro
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
    expose:
      - 8000
    ports:
      - 8181:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s

  de-identification:
    build:
        context: ./
        dockerfile: ./docker/trf-deid/Dockerfile
        args:
          - CMS_MODEL_NAME=De-identification model
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms-dev_trf-deid
    restart: always
    networks:
      - cms-dev
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - ./docker/trf-deid/.env:/app/envs/.env:ro
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
    expose:
      - 8000
    ports:
      - 8182:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s

  medcat-deid:
    build:
        context: ./
        dockerfile: ./docker/medcat-deid/Dockerfile
        args:
          - CMS_MODEL_NAME=De-Identification MedCAT model
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms-dev_medcat-deid
    restart: always
    networks:
      - cms-dev
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - retrained-models:/app/model/retrained
      - ./docker/medcat-snomed/.env:/app/envs/.env:ro
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
    expose:
      - 8000
    ports:
      - 8183:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s

  medcat-umls:
    build:
      context: ./
      dockerfile: ./docker/medcat-umls/Dockerfile
      args:
        - CMS_MODEL_NAME=UMLS MedCAT model
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - NO_PROXY=$NO_PROXY
    container_name: cms-dev_medcat-umls
    restart: always
    networks:
      - cms-dev
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - retrained-models:/app/model/retrained
      - ./docker/medcat-snomed/.env:/app/envs/.env:ro
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
    expose:
      - 8000
    ports:
      - 8184:8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/info" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  retrained-models:
    driver: local

networks:
  cms-dev:
    driver: bridge