version: "3.6"

services:

  medcat-1-2:
    build:
        context: ./
        dockerfile: ./docker/medcat-1-2/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms_medcat-1-2
    restart: always
    networks:
      - cms
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - retrained-models:/app/model/retrained
      - ./docker/medcat-1-2/.env_snomed:/app/envs/.env:ro
      - mlruns:/app/mlruns
    environment:
      - MLFLOW_DB_USERNAME=$MLFLOW_DB_USERNAME
      - MLFLOW_DB_PASSWORD=$MLFLOW_DB_PASSWORD
      - BASE_MODEL_ORIGIN=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    expose:
      - 8000
    ports:
      - 8180:8000
#    depends_on:
#      - mlflow-db

  medcat-1-2-icd10:
    build:
        context: ./
        dockerfile: ./docker/medcat-1-2/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms_medcat-1-2-icd10
    restart: always
    networks:
      - cms
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - retrained-models:/app/model/retrained
      - ./docker/medcat-1-2/.env_icd10:/app/envs/.env:ro
      - mlruns:/app/mlruns
    environment:
      - MLFLOW_DB_USERNAME=$MLFLOW_DB_USERNAME
      - MLFLOW_DB_PASSWORD=$MLFLOW_DB_PASSWORD
      - BASE_MODEL_ORIGIN=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    expose:
      - 8000
    ports:
      - 8181:8000
#    depends_on:
#      - mlflow-db

  de-identification:
    build:
        context: ./
        dockerfile: ./docker/de-id/Dockerfile
        args:
          - HTTP_PROXY=$HTTP_PROXY
          - HTTPS_PROXY=$HTTPS_PROXY
          - NO_PROXY=$NO_PROXY
    container_name: cms_medcat-de-id
    restart: always
    networks:
      - cms
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
      - ./docker/de-id/.env:/app/envs/.env:ro
    environment:
      - BASE_MODEL_ORIGIN=$MODEL_PACKAGE_FULL_PATH
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    expose:
      - 8000
    ports:
      - 8182:8000

  mlflow-db:
    image: postgres:latest
    container_name: cms_mlflow-db
    restart: always
    networks:
      - cms
    environment:
      - POSTGRES_DB=mlflow-backend-store
      - POSTGRES_USER=$MLFLOW_DB_USERNAME
      - POSTGRES_PASSWORD=$MLFLOW_DB_PASSWORD
    volumes:
      - mlflow-backend-store:/var/lib/postgresql/data
    expose:
      - 5432

  mlflow-ui:
    build:
      context: ./
      dockerfile: ./docker/mlflow/Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - NO_PROXY=$NO_PROXY
    container_name: cms_mlflow-ui
    restart: always
    networks:
      - cms
    volumes:
      - mlruns:/opt/mlflow/mlruns:ro
    environment:
      - MLFLOW_DB_USERNAME=$MLFLOW_DB_USERNAME
      - MLFLOW_DB_PASSWORD=$MLFLOW_DB_PASSWORD
      - DEFAULT_ARTIFACT_ROOT=/opt/mlflow/mlruns
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    expose:
      - 5000
    ports:
      - 8200:5000
#    depends_on:
#      - mlflow-db

  proxy:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - HTTPS_PROXY=$HTTPS_PROXY
        - NO_PROXY=$NO_PROXY
    container_name: cms_proxy
    restart: always
    networks:
      - cms
    volumes:
      - ./docker/nginx/etc/nginx/root-ca.pem:/etc/nginx/root-ca.pem:ro
      - ./docker/nginx/etc/nginx/root-ca.key:/etc/nginx/root-ca.key:ro
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/etc/nginx/cors.conf:/etc/nginx/cors.conf:ro
      - ./docker/nginx/etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./docker/nginx/etc/nginx/.htpasswd:/etc/nginx/.htpasswd
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    ports:
      - 28180:28180
      - 28181:28181
      - 28182:28182
      - 28200:28200
#    depends_on:
#      - medcat-1-2
#      - medcat-1-2-icd10
#      - de-identification
#      - mlflow-ui

volumes:
  retrained-models:
    driver: local
  mlruns:
    driver: local
  mlflow-backend-store:
    driver: local

networks:
  cms:
    driver: bridge