# This is for spinning up core services as single hosts in the DEV environment
version: "3.6"

services:

  medcat-snomed:
    extends:
      file: ./docker-compose.yml
      service: medcat-snomed
    image: cogstack-model-serve_medcat-snomed:dev
    container_name: dev-cms_medcat-snomed
    volumes:
      - ${MODEL_PACKAGE_FULL_PATH}:/app/model/model.zip:ro
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - MLFLOW_S3_ENDPOINT_URL=
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-file:/tmp/mlruns}
      - MLFLOW_TRACKING_USERNAME=
      - MLFLOW_TRACKING_PASSWORD=
      - MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING=${MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING:-false}
      - GELF_INPUT_URI=
      - AUTH_USER_ENABLED=${AUTH_USER_ENABLED:-false}
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - AUTH_ACCESS_TOKEN_EXPIRE_SECONDS=${AUTH_ACCESS_TOKEN_EXPIRE_SECONDS:-3600}
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL:-sqlite+aiosqlite:///./cms-users.db}
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=localhost
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - NO_PROXY=localhost

  medcat-icd10:
    extends:
      file: ./docker-compose.yml
      service: medcat-icd10
    image: cogstack-model-serve_medcat-icd10:dev
    container_name: dev-cms_medcat-icd10
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - MLFLOW_S3_ENDPOINT_URL=
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-file:/tmp/mlruns}
      - MLFLOW_TRACKING_USERNAME=
      - MLFLOW_TRACKING_PASSWORD=
      - MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING=${MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING:-false}
      - GELF_INPUT_URI=
      - AUTH_USER_ENABLED=${AUTH_USER_ENABLED:-false}
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - AUTH_ACCESS_TOKEN_EXPIRE_SECONDS=${AUTH_ACCESS_TOKEN_EXPIRE_SECONDS:-3600}
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL:-sqlite+aiosqlite:///./cms-users.db}
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=localhost
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - NO_PROXY=localhost

  de-identification:
    extends:
      file: ./docker-compose.yml
      service: de-identification
    image: cogstack-model-serve_de-identification:dev
    container_name: dev-cms_trf-deid
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - MLFLOW_S3_ENDPOINT_URL=
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-file:/tmp/mlruns}
      - MLFLOW_TRACKING_USERNAME=
      - MLFLOW_TRACKING_PASSWORD=
      - MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING=${MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING:-false}
      - GELF_INPUT_URI=
      - AUTH_USER_ENABLED=${AUTH_USER_ENABLED:-false}
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - AUTH_ACCESS_TOKEN_EXPIRE_SECONDS=${AUTH_ACCESS_TOKEN_EXPIRE_SECONDS:-3600}
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL:-sqlite+aiosqlite:///./cms-users.db}
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=localhost
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - NO_PROXY=localhost

  medcat-deid:
    extends:
      file: ./docker-compose.yml
      service: medcat-deid
    image: cogstack-model-serve_medcat-deid:dev
    container_name: dev-cms_medcat-deid
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - MLFLOW_S3_ENDPOINT_URL=
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-file:/tmp/mlruns}
      - MLFLOW_TRACKING_USERNAME=
      - MLFLOW_TRACKING_PASSWORD=
      - MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING=${MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING:-false}
      - GELF_INPUT_URI=
      - AUTH_USER_ENABLED=${AUTH_USER_ENABLED:-false}
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - AUTH_ACCESS_TOKEN_EXPIRE_SECONDS=${AUTH_ACCESS_TOKEN_EXPIRE_SECONDS:-3600}
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL:-sqlite+aiosqlite:///./cms-users.db}
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=localhost
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - NO_PROXY=localhost

  medcat-umls:
    extends:
      file: ./docker-compose.yml
      service: medcat-umls
    image: cogstack-model-serve_medcat-umls:dev
    container_name: dev-cms_medcat-umls
    environment:
      - BASE_MODEL_FULL_PATH=$MODEL_PACKAGE_FULL_PATH
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - MLFLOW_S3_ENDPOINT_URL=
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-file:/tmp/mlruns}
      - MLFLOW_TRACKING_USERNAME=
      - MLFLOW_TRACKING_PASSWORD=
      - MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING=${MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING:-false}
      - GELF_INPUT_URI=
      - AUTH_USER_ENABLED=${AUTH_USER_ENABLED:-false}
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - AUTH_ACCESS_TOKEN_EXPIRE_SECONDS=${AUTH_ACCESS_TOKEN_EXPIRE_SECONDS:-3600}
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL:-sqlite+aiosqlite:///./cms-users.db}
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=localhost
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - NO_PROXY=localhost

volumes:
  retrained-models:
    driver: local

networks:
  cms:
    driver: bridge