version: "3.6"

name: cms

services:

  auth-db:
    image: postgres:14
    restart: always
    networks:
      - cogstack-model-serve_cms
    environment:
      - POSTGRES_DB=cms-users
      - POSTGRES_USER=$AUTH_DB_USERNAME
      - POSTGRES_PASSWORD=$AUTH_DB_PASSWORD
    volumes:
      - auth-users:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 60s
      timeout: 20s
      retries: 3

volumes:
  auth-users:
    driver: local

networks:
  cogstack-model-serve_cms:
    external: true