[build-system]
requires = ["setuptools", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cogstack-model-serve"
authors = [{name = "Xi Bai", email = "baixiac@gmail.com"}]
description = "A model serving and governance system for CogStack NLP solutions"
requires-python = ">=3.8,<3.12"
dynamic = ["version"]
dependencies = [
    "medcat~=1.15.2; python_version >= '3.9'",
    "medcat~=1.13.1; python_version < '3.9'",
#    "transformers~=4.43.0",
    "torch<2.5.0; python_version < '3.9'",
    "datasets>=2.21.0",
    "blis<1.0.0",
    "fastapi~=0.115.0",
    "uvicorn~=0.29.0",
    "python-multipart~=0.0.5",
    "ijson~=3.1.4",
    "python-dotenv~=0.20.0",
    "mlflow~=2.16.2",
    "psycopg2-binary~=2.9.4",
    "boto3~=1.28.84",
    "typer~=0.15.1",
    "prometheus-fastapi-instrumentator~=7.0.0",
    "sentencepiece~=0.2.0",
    "slowapi~=0.1.7",
    "graypy~=2.1.0",
    "fastapi-users~=11.0.0",
    "fastapi-users-db-sqlalchemy~=5.0.0",
    "asyncpg~=0.27.0",
    "aiosqlite~=0.19.0",
    "evaluate~=0.4.1",
    "websockets~=12.0",
    "pynvml~=11.5.3",
    "toml~=0.10.2",
    "peft<0.14.0",
    "huggingface-hub~=0.30.0"
]
readme = "README.md"
keywords = ["natural-language-processing", "electronic-health-records", "clinical-data"]
license = {text = "Elastic License 2.0"}
classifiers=[
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Framework :: FastAPI",
]

[project.urls]
Homepage = "https://github.com/CogStack/CogStack-ModelServe"
Documentation = "https://cogstack.github.io/CogStack-ModelServe/docs/cogstack_model_serve_apis.html"

[dependency-groups]
dev = [
    "pytest~=7.1.2",
    "pytest-mock~=3.7.0",
    "pytest-timeout~=2.1.0",
    "pytest-random-order~=1.1.0",
    "pytest-asyncio~=0.23.7",
    "pytest-cov~=4.1.0",
    "pytest-bdd~=7.2.0",
    "httpx~=0.24.1",
    "mypy==1.8.0",
    "ruff==0.6.9",
    "locust<2.32.0",
    "typer-cli~=0.15.1",
    "types-toml==0.10.8.20240310",
]
docs = [
    "sphinx~=7.1.2",
    "sphinx-autoapi~=3.5.0",
    "sphinx-autodoc-typehints~=2.0.1",
    "sphinx-rtd-theme~=3.0.2",
]

# For pip versions not supporting PEP 735
[project.optional-dependencies]
dev = [
    "pytest~=7.1.2",
    "pytest-mock~=3.7.0",
    "pytest-timeout~=2.1.0",
    "pytest-random-order~=1.1.0",
    "pytest-asyncio~=0.23.7",
    "pytest-cov~=4.1.0",
    "pytest-bdd~=7.2.0",
    "httpx~=0.24.1",
    "mypy==1.8.0",
    "ruff==0.6.9",
    "locust<2.32.0",
    "typer-cli~=0.15.1",
    "types-toml==0.10.8.20240310",
]
docs = [
    "sphinx~=7.1.2",
    "sphinx-autoapi~=3.5.0",
    "sphinx-autodoc-typehints~=2.0.1",
    "sphinx-rtd-theme~=3.0.2",
]
vllm = [
    "vllm~=0.8.5",
]

[tool.setuptools]
packages = ["app"]

[tool.setuptools.dynamic]
version = {attr = "app.__version__"}

[project.scripts]
cms = "app.cli.cli:cmd_app"

[tool.ruff]
include = [
    "app/model_services/*.py",
    "app/management/*.py",
    "app/processors/*.py",
    "app/api/*.py",
    "app/api/routers/*.py",
    "app/api/auth/*.py",
    "app/cli/*.py",
    "app/trainers/*.py",
    "app/*.py",
    "scripts/generate_annotations.py",
    "scripts/hf_model_packager.py",
    "scripts/medcat_concept_diff.py",
    "scripts/medcat_config_diff.py",
    "scripts/remove_model_version.py",
    "scripts/generate_annotations.py",
    "tests/",
]

line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "C90"]
ignore = ["E501", "E226", "C901"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.mypy]
ignore_missing_imports = true
no_implicit_optional = true
allow_redefinition = true
follow_imports = "normal"
warn_redundant_casts = true
warn_unused_ignores = false
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true
disable_error_code = "method-assign"
plugins = [
  "pydantic.mypy"
]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
