global:
  scrape_interval: 15s
  evaluation_interval: 60s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 60s
    static_configs:
    - targets:
      - "localhost:9090"

  - job_name: "cms_medcat-snomed"
    scrape_interval: 15s
    static_configs:
    - targets:
      - "medcat-snomed:8000"

  - job_name: "cms_medcat-icd10"
    scrape_interval: 15s
    static_configs:
    - targets:
      - "medcat-icd10:8000"

  - job_name: "cms_medcat-opcs4"
    scrape_interval: 15s
    static_configs:
    - targets:
      - "medcat-opcs4:8000"

  - job_name: "cms_medcat-deid"
    scrape_interval: 15s
    static_configs:
    - targets:
      - "medcat-deid:8000"

  - job_name: "cms_medcat-umls"
    scrape_interval: 15s
    static_configs:
    - targets:
      - "medcat-umls:8000"

  - job_name: "cms_huggingface-ner"
    scrape_interval: 15s
    static_configs:
    - targets:
      - "huggingface-ner:8000"

  - job_name: "cms_cadvisor"
    scrape_interval: 15s
    static_configs:
    - targets:
      - "cadvisor:8080"
    metric_relabel_configs:
      - source_labels: [ container_label_org_cogstack_model_serve ]
        regex: ^$
        action: drop
