class PromptFactory:

    _ALPACA = (
        "{% if messages[0]['role'] == 'system' %}"
          "{% set loop_messages = messages[1:] %}"
          "{% set system_message = messages[0]['content'].strip() + '\n' %}"
        "{% else %}"
          "{% set loop_messages = messages %}"
          "{% set system_message = '' %}"
        "{% endif %}"
        "{% for message in loop_messages %}"
          "{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}"
            "{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}"
          "{% endif %}"
          "{% if loop.index0 == 0 %}"
            "{% set content = system_message + message['content'] %}"
          "{% else %}"
            "{% set content = message['content'] %}"
          "{% endif %}"

          "{% if message['role'] == 'user' %}"
            "{{ '### Instruction:\n' + content.strip() + '\n\n'}}"
          "{% elif message['role'] == 'assistant' %}"
            "{{ '### Response:\n'  + content.strip() + '\n\n' }}"
          "{% endif %}"
        "{% endfor %}"
        "{% if add_generation_prompt %}"
          "{{ '### Response:\n' }}"
        "{% endif %}"
    )

    _CHAT_ML = (
        "{% for message in messages %}"
            "{{'<|im_start|>' + message['role'] + '\n' + message['content'].strip() + '<|im_end|>' + '\n'}}"
        "{% endfor %}"
        "{% if add_generation_prompt %}"
            "{{'<|im_start|>assistant\n'}}"
        "{% endif %}"
    )

    _DEFAULT = (
        "{% for message in messages %}"
            "{% if message['role'] == 'user' %}"
                "{{'<|user|>\n' + message['content'] + eos_token}}"
            "{% elif message['role'] == 'system' %}"
                "{{'<|system|>\n' + message['content'] + eos_token}}"
            "{% elif message['role'] == 'assistant' %}"
                "{{'<|assistant|>\n' + message['content'] + eos_token}}"
            "{% endif %}"
            "{% if loop.last and add_generation_prompt %}"
                "{{'<|assistant|>'}}"
            "{% endif %}"
        "{% endfor %}"
    )

    _FALCON = (
        "{% if messages[0]['role'] == 'system' %}"
          "{% set loop_messages = messages[1:] %}"
          "{% set system_message = messages[0]['content'] %}"
        "{% else %}"
          "{% set loop_messages = messages %}"
          "{% set system_message = '' %}"
        "{% endif %}"
        "{% for message in loop_messages %}"
          "{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}"
            "{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}"
          "{% endif %}"
          "{% if loop.index0 == 0 %}"
            "{{ system_message.strip() }}"
          "{% endif %}"
          "{{ '\n\n' + message['role'].title() + ': ' + message['content'].strip().replace('\r\n', '\n').replace('\n\n', '\n') }}"
        "{% endfor %}"
        "{% if add_generation_prompt %}"
          "{ '\n\nAssistant:' }}"
        "{% endif %}"
    )

    _GEMMA = (
        "{% if messages[0]['role'] == 'system' %}"
          "{% set loop_messages = messages[1:] %}"
          "{% set system_message = messages[0]['content'].strip() + '\n\n' %}"
        "{% else %}"
          "{% set loop_messages = messages %}"
          "{% set system_message = '' %}"
        "{% endif %}"
        "{% for message in loop_messages %}"
          "{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}"
            "{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}"
          "{% endif %}"
          "{% if loop.index0 == 0 %}"
            "{% set content = system_message + message['content'] %}"
          "{% else %}"
            "{% set content = message['content'] %}"
          "{% endif %}"
          "{% if (message['role'] == 'assistant') %}"
            "{% set role = 'model' %}"
          "{% else %}"
            "{% set role = message['role'] %}"
          "{% endif %}"
          "{{ '<start_of_turn>' + role + '\n' + content.strip() + '<end_of_turn>\n' }}"
        "{% endfor %}"
        "{% if add_generation_prompt %}"
          "{{'<start_of_turn>model\n'}}"
        "{% endif %}"
    )

    _LLAMA_2 = (
        "{% if messages[0]['role'] == 'system' %}"
          "{% set loop_messages = messages[1:] %}"
          "{% set system_message = '<<SYS>>\n' + messages[0]['content'].strip() + '\n<</SYS>>\n\n' %}"
        "{% else %}"
          "{% set loop_messages = messages %}"
          "{% set system_message = '' %}"
        "{% endif %}"
        "{% for message in loop_messages %}"
          "{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}"
            "{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}"
          "{% endif %}"
          "{% if loop.index0 == 0 %}"
            "{% set content = system_message + message['content'] %}"
          "{% else %}"
            "{% set content = message['content'] %}"
          "{% endif %}"
          "{% if message['role'] == 'user' %}"
            "{{ bos_token + '[INST] ' + content.strip() + ' [/INST]' }}"
          "{% elif message['role'] == 'assistant' %}"
            "{{ ' '  + content.strip() + ' ' + eos_token }}"
          "{% endif %}"
        "{% endfor %}"
    )

    _LLAMA_3 = (
        "{{ bos_token }}"
        "{% if messages[0]['role'] == 'system' %}"
          "{% set loop_messages = messages[1:] %}"
          "{% set system_message = '<|start_header_id|>' + 'system' + '<|end_header_id|>\n\n' + messages[0]['content'].strip() + '<|eot_id|>' %}"
        "{% else %}"
          "{% set loop_messages = messages %}"
          "{% set system_message = '' %}"
        "{% endif %}"
        "{% for message in loop_messages %}"
          "{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}"
            "{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}"
          "{% endif %}"
          "{% if loop.index0 == 0 %}"
            "{{ system_message }}"
          "{% endif %}"
          "{{ '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n' + message['content'].strip() + '<|eot_id|>' }}"
          "{% if loop.last and message['role'] == 'user' and add_generation_prompt %}"
            "{{ '<|start_header_id|>' + 'assistant' + '<|end_header_id|>\n\n' }}"
          "{% endif %}"
        "{% endfor %}"
    )

    _MISTRAL = (
        "{{ bos_token }}"
        "{% if messages[0]['role'] == 'system' %}"
          "{% set loop_messages = messages[1:] %}"
          "{% set system_message = messages[0]['content'].strip() + '\n\n' %}"
        "{% else %}"
          "{% set loop_messages = messages %}"
          "{% set system_message = '' %}"
        "{% endif %}"
        "{% for message in loop_messages %}"
          "{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}"
            "{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}"
          "{% endif %}"
          "{% if loop.index0 == 0 %}"
            "{% set content = system_message + message['content'] %}"
          "{% else %}"
            "{% set content = message['content'] %}"
          "{% endif %}"
          "{% if message['role'] == 'user' %}"
            "{{ '[INST] ' + content.strip() + ' [/INST]' }}"
          "{% elif message['role'] == 'assistant' %}"
            "{{ content.strip() + eos_token}}"
          "{% endif %}"
        "{% endfor %}"
    )

    _PHI_2 = (
        "{% if messages[0]['role'] == 'system' %}"
          "{% set loop_messages = messages[1:] %}"
          "{% set system_message = messages[0]['content'].strip() + '\n\n' %}"
        "{% else %}"
          "{% set loop_messages = messages %}"
          "{% set system_message = '' %}"
        "{% endif %}"
        "{% for message in loop_messages %}"
          "{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}"
            "{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}"
          "{% endif %}"
          "{% if loop.index0 == 0 %}"
            "{% set content = system_message + message['content'] %}"
          "{% else %}"
            "{% set content = message['content'] %}"
          "{% endif %}"
          "{% if message['role'] == 'user' %}"
            "{{ 'Instruct: ' + content.strip() + '\n' }}"
          "{% elif message['role'] == 'assistant' %}"
            "{{ 'Output: '  + content.strip() + '\n' }}"
          "{% endif %}"
        "{% endfor %}"
        "{% if add_generation_prompt %}"
          "{{ 'Output:' }}"
        "{% endif %}"
    )

    _PHI_3 = (
        "{{ bos_token }}"
        "{% for message in messages %}"
            "{% if (message['role'] == 'system') %}"
                "{{'<|system|>' + '\n' + message['content'].strip() + '<|end|>' + '\n'}}"
            "{% elif (message['role'] == 'user') %}"
                "{{'<|user|>' + '\n' + message['content'].strip() + '<|end|>' + '\n' + '<|assistant|>' + '\n'}}"
            "{% elif message['role'] == 'assistant' %}"
                "{{message['content'].strip() + '<|end|>' + '\n'}}"
            "{% endif %}"
        "{% endfor %}"
    )

    _QWEN = (
        "{% for message in messages %}"
          "{% if loop.first and messages[0]['role'] != 'system' %}"
            "{{ '<|im_start|>system\nYou are a helpful assistant<|im_end|>\n' }}"
          "{% endif %}"
          "{{'<|im_start|>' + message['role'] + '\n' + message['content'].strip() }}"
          "{% if (loop.last and add_generation_prompt) or not loop.last %}"
            "{{ '<|im_end|>' + '\n'}}"
          "{% endif %}"
        "{% endfor %}"
        "{% if add_generation_prompt and messages[-1]['role'] != 'assistant' %}"
          "{{ '<|im_start|>assistant\n' }}"
        "{% endif %}"
    )

    _GPT_OSS = (
      "{#-"
      "  In addition to the normal inputs of `messages` and `tools`, this template also accepts the"
      "  following kwargs:"
      "  - \"builtin_tools\": A list, can contain \"browser\" and/or \"python\"."
      "  - \"model_identity\": A string that optionally describes the model identity."
      "  - \"reasoning_effort\": A string that describes the reasoning effort, defaults to \"medium\"."
      " #}"
      ""
      "{#- Tool Definition Rendering ============================================== #}"
      "{%- macro render_typescript_type(param_spec, required_params, is_nullable=false) -%}"
      "    {%- if param_spec.type == \"array\" -%}"
      "        {%- if param_spec['items'] -%}"
      "            {%- if param_spec['items']['type'] == \"string\" -%}"
      "                {{- \"string[]\" }}"
      "            {%- elif param_spec['items']['type'] == \"number\" -%}"
      "                {{- \"number[]\" }}"
      "            {%- elif param_spec['items']['type'] == \"integer\" -%}"
      "                {{- \"number[]\" }}"
      "            {%- elif param_spec['items']['type'] == \"boolean\" -%}"
      "                {{- \"boolean[]\" }}"
      "            {%- else -%}"
      "                {%- set inner_type = render_typescript_type(param_spec['items'], required_params) -%}"
      "                {%- if inner_type == \"object | object\" or inner_type|length > 50 -%}"
      "                    {{- \"any[]\" }}"
      "                {%- else -%}"
      "                    {{- inner_type + \"[]\" }}"
      "                {%- endif -%}"
      "            {%- endif -%}"
      "            {%- if param_spec.nullable -%}"
      "                {{- \" | null\" }}"
      "            {%- endif -%}"
      "        {%- else -%}"
      "            {{- \"any[]\" }}"
      "            {%- if param_spec.nullable -%}"
      "                {{- \" | null\" }}"
      "            {%- endif -%}"
      "        {%- endif -%}"
      "    {%- elif param_spec.type is defined and param_spec.type is iterable and param_spec.type is not string and param_spec.type is not mapping and param_spec.type[0] is defined -%}"
      "        {#- Handle array of types like [\"object\", \"object\"] from Union[dict, list] #}"
      "        {%- if param_spec.type | length > 1 -%}"
      "            {{- param_spec.type | join(\" | \") }}"
      "        {%- else -%}"
      "            {{- param_spec.type[0] }}"
      "        {%- endif -%}"
      "    {%- elif param_spec.oneOf -%}"
      "        {#- Handle oneOf schemas - check for complex unions and fallback to any #}"
      "        {%- set has_object_variants = false -%}"
      "        {%- for variant in param_spec.oneOf -%}"
      "            {%- if variant.type == \"object\" -%}"
      "                {%- set has_object_variants = true -%}"
      "            {%- endif -%}"
      "        {%- endfor -%}"
      "        {%- if has_object_variants and param_spec.oneOf|length > 1 -%}"
      "            {{- \"any\" }}"
      "        {%- else -%}"
      "            {%- for variant in param_spec.oneOf -%}"
      "                {{- render_typescript_type(variant, required_params) -}}"
      "                {%- if variant.description %}"
      "                    {{- \"// \" + variant.description }}"
      "                {%- endif -%}"
      "                {%- if variant.default is defined %}"
      "                    {{ \"// default: \" + variant.default|tojson }}"
      "                {%- endif -%}"
      "                {%- if not loop.last %}"
      "                    {{- \" | \" }}"
      "                {% endif -%}"
      "            {%- endfor -%}"
      "        {%- endif -%}"
      "    {%- elif param_spec.type == \"string\" -%}"
      "        {%- if param_spec.enum -%}"
      "            {{- '\"' + param_spec.enum|join('\" | \"') + '\"' -}}"
      "        {%- else -%}"
      "            {{- \"string\" }}"
      "            {%- if param_spec.nullable %}"
      "                {{- \" | null\" }}"
      "            {%- endif -%}"
      "        {%- endif -%}"
      "    {%- elif param_spec.type == \"number\" -%}"
      "        {{- \"number\" }}"
      "    {%- elif param_spec.type == \"integer\" -%}"
      "        {{- \"number\" }}"
      "    {%- elif param_spec.type == \"boolean\" -%}"
      "        {{- \"boolean\" }}"
      ""
      "    {%- elif param_spec.type == \"object\" -%}"
      "        {%- if param_spec.properties -%}"
      "            {{- \"{\\n\" }}"
      "            {%- for prop_name, prop_spec in param_spec.properties.items() -%}"
      "                {{- prop_name -}}"
      "                {%- if prop_name not in (param_spec.required or []) -%}"
      "                    {{- \"?\" }}"
      "                {%- endif -%}"
      "                {{- \": \" }}"
      "                {{ render_typescript_type(prop_spec, param_spec.required or []) }}"
      "                {%- if not loop.last -%}"
      "                    {{- \", \" }}"
      "                {%- endif -%}"
      "            {%- endfor -%}"
      "            {{- \"}\" }}"
      "        {%- else -%}"
      "            {{- \"object\" }}"
      "        {%- endif -%}"
      "    {%- else -%}"
      "        {{- \"any\" }}"
      "    {%- endif -%}"
      "{%- endmacro -%}"
      ""
      "{%- macro render_tool_namespace(namespace_name, tools) -%}"
      "    {{- \"## \" + namespace_name + \"\\n\\n\" }}"
      "    {{- \"namespace \" + namespace_name + \" {\\n\\n\" }}"
      "    {%- for tool in tools %}"
      "        {%- set tool = tool.function %}"
      "        {{- \"// \" + tool.description + \"\\n\" }}"
      "        {{- \"type \"+ tool.name + \" = \" }}"
      "        {%- if tool.parameters and tool.parameters.properties %}"
      "            {{- \"(_: {\\n\" }}"
      "            {%- for param_name, param_spec in tool.parameters.properties.items() %}"
      "                {%- if param_spec.description %}"
      "                    {{- \"// \" + param_spec.description + \"\\n\" }}"
      "                {%- endif %}"
      "                {{- param_name }}"
      "                {%- if param_name not in (tool.parameters.required or []) -%}"
      "                    {{- \"?\" }}"
      "                {%- endif -%}"
      "                {{- \": \" }}"
      "                {{- render_typescript_type(param_spec, tool.parameters.required or []) }}"
      "                {%- if param_spec.default is defined -%}"
      "                    {%- if param_spec.enum %}"
      "                        {{- \", // default: \" + param_spec.default }}"
      "                    {%- elif param_spec.oneOf %}"
      "                        {{- \"// default: \" + param_spec.default }}"
      "                    {%- else %}"
      "                        {{- \", // default: \" + param_spec.default|tojson }}"
      "                    {%- endif -%}"
      "                {%- endif -%}"
      "                {%- if not loop.last %}"
      "                    {{- \",\\n\" }}"
      "                {%- else %}"
      "                    {{- \",\\n\" }}"
      "                {%- endif -%}"
      "            {%- endfor %}"
      "            {{- \"}) => any;\\n\\n\" }}"
      "        {%- else -%}"
      "            {{- \"() => any;\\n\\n\" }}"
      "        {%- endif -%}"
      "    {%- endfor %}"
      "    {{- \"} // namespace \" + namespace_name }}"
      "{%- endmacro -%}"
      ""
      "{%- macro render_builtin_tools(browser_tool, python_tool) -%}"
      "    {%- if browser_tool %}"
      "        {{- \"## browser\\n\\n\" }}"
      "        {{- \"// Tool for browsing.\\n\" }}"
      "        {{- \"// The `cursor` appears in brackets before each browsing display: `[{cursor}]`.\\n\" }}"
      "        {{- \"// Cite information from the tool using the following format:\\n\" }}"
      "        {{- \"// `【{cursor}†L{line_start}(-L{line_end})?】`, for example: `【6†L9-L11】` or `【8†L3】`.\\n\" }}"
      "        {{- \"// Do not quote more than 10 words directly from the tool output.\\n\" }}"
      "        {{- \"// sources=web (default: web)\\n\" }}"
      "        {{- \"namespace browser {\\n\\n\" }}"
      "        {{- \"// Searches for information related to `query` and displays `topn` results.\\n\" }}"
      "        {{- \"type search = (_: {\\n\" }}"
      "        {{- \"query: string,\\n\" }}"
      "        {{- \"topn?: number, // default: 10\\n\" }}"
      "        {{- \"source?: string,\\n\" }}"
      "        {{- \"}) => any;\\n\\n\" }}"
      "        {{- \"// Opens the link `id` from the page indicated by `cursor` starting at line number `loc`, showing `num_lines` lines.\\n\" }}"
      "        {{- \"// Valid link ids are displayed with the formatting: `【{id}†.*】`.\\n\" }}"
      "        {{- \"// If `cursor` is not provided, the most recent page is implied.\\n\" }}"
      "        {{- \"// If `id` is a string, it is treated as a fully qualified URL associated with `source`.\\n\" }}"
      "        {{- \"// If `loc` is not provided, the viewport will be positioned at the beginning of the document or centered on the most relevant passage, if available.\\n\" }}"
      "        {{- \"// Use this function without `id` to scroll to a new location of an opened page.\\n\" }}"
      "        {{- \"type open = (_: {\\n\" }}"
      "        {{- \"id?: number | string, // default: -1\\n\" }}"
      "        {{- \"cursor?: number, // default: -1\\n\" }}"
      "        {{- \"loc?: number, // default: -1\\n\" }}"
      "        {{- \"num_lines?: number, // default: -1\\n\" }}"
      "        {{- \"view_source?: boolean, // default: false\\n\" }}"
      "        {{- \"source?: string,\\n\" }}"
      "        {{- \"}) => any;\\n\\n\" }}"
      "        {{- \"// Finds exact matches of `pattern` in the current page, or the page given by `cursor`.\\n\" }}"
      "        {{- \"type find = (_: {\\n\" }}"
      "        {{- \"pattern: string,\\n\" }}"
      "        {{- \"cursor?: number, // default: -1\\n\" }}"
      "        {{- \"}) => any;\\n\\n\" }}"
      "        {{- \"} // namespace browser\\n\\n\" }}"
      "    {%- endif -%}"
      ""
      "    {%- if python_tool %}"
      "        {{- \"## python\\n\\n\" }}"
      "        {{- \"Use this tool to execute Python code in your chain of thought. The code will not be shown to the user. This tool should be used for internal reasoning, but not for code that is intended to be visible to the user (e.g. when creating plots, tables, or files).\\n\\n\" }}"
      "        {{- \"When you send a message containing Python code to python, it will be executed in a stateful Jupyter notebook environment. python will respond with the output of the execution or time out after 120.0 seconds. The drive at '/mnt/data' can be used to save and persist user files. Internet access for this session is UNKNOWN. Depends on the cluster.\\n\\n\" }}"
      "    {%- endif -%}"
      "{%- endmacro -%}"
      ""
      "{#- System Message Construction ============================================ #}"
      "{%- macro build_system_message() -%}"
      "    {%- if model_identity is not defined %}"
      "        {%- set model_identity = \"You are ChatGPT, a large language model trained by OpenAI.\" %}"
      "    {%- endif %}"
      "    {{- model_identity + \"\\n\" }}"
      "    {{- \"Knowledge cutoff: 2024-06\\n\" }}"
      "    {{- \"Current date: \" + strftime_now(\"%Y-%m-%d\") + \"\\n\\n\" }}"
      "    {%- if reasoning_effort is not defined %}"
      "        {%- set reasoning_effort = \"medium\" %}"
      "    {%- endif %}"
      "    {{- \"Reasoning: \" + reasoning_effort + \"\\n\\n\" }}"
      "    {%- if builtin_tools %}"
      "        {{- \"# Tools\\n\\n\" }}"
      "        {%- set available_builtin_tools = namespace(browser=false, python=false) %}"
      "        {%- for tool in builtin_tools %}"
      "            {%- if tool == \"browser\" %}"
      "                {%- set available_builtin_tools.browser = true %}"
      "            {%- elif tool == \"python\" %}"
      "                {%- set available_builtin_tools.python = true %}"
      "            {%- endif %}"
      "        {%- endfor %}"
      "        {{- render_builtin_tools(available_builtin_tools.browser, available_builtin_tools.python) }}"
      "    {%- endif -%}"
      "    {{- \"# Valid channels: analysis, commentary, final. Channel must be included for every message.\" }}"
      "    {%- if tools -%}"
      "        {{- \"\\nCalls to these tools must go to the commentary channel: 'functions'.\" }}"
      "    {%- endif -%}"
      "{%- endmacro -%}"
      ""
      "{#- Main Template Logic ================================================= #}"
      "{#- Set defaults #}"
      ""
      "{#- Render system message #}"
      "{{- \"<|start|>system<|message|>\" }}"
      "{{- build_system_message() }}"
      "{{- \"<|end|>\" }}"
      ""
      "{#- Extract developer message #}"
      "{%- if messages[0].role == \"developer\" or messages[0].role == \"system\" %}"
      "    {%- set developer_message = messages[0].content %}"
      "    {%- set loop_messages = messages[1:] %}"
      "{%- else %}"
      "    {%- set developer_message = \"\" %}"
      "    {%- set loop_messages = messages %}"
      "{%- endif %}"
      ""
      "{#- Render developer message #}"
      "{%- if developer_message or tools %}"
      "    {{- \"<|start|>developer<|message|>\" }}"
      "    {%- if developer_message %}"
      "        {{- \"# Instructions\\n\\n\" }}"
      "        {{- developer_message }}"
      "        {{- \"\\n\\n\" }}"
      "    {%- endif %}"
      "    {%- if tools -%}"
      "        {{- \"# Tools\\n\\n\" }}"
      "        {{- render_tool_namespace(\"functions\", tools) }}"
      "    {%- endif -%}"
      "    {{- \"<|end|>\" }}"
      "{%- endif %}"
      ""
      "{#- Render messages #}"
      "{%- set last_tool_call = namespace(name=none) %}"
      "{%- for message in loop_messages -%}"
      "    {#- At this point only assistant/user/tool messages should remain #}"
      "    {%- if message.role == 'assistant' -%}"
      "        {#- Checks to ensure the messages are being passed in the format we expect #}"
      "        {%- if \"content\" in message %}"
      "            {%- if \"<|channel|>analysis<|message|>\" in message.content or \"<|channel|>final<|message|>\" in message.content %}"
      "                {{- raise_exception(\"You have passed a message containing <|channel|> tags in the content field. Instead of doing this, you should pass analysis messages (the string between '<|message|>' and '<|end|>') in the 'thinking' field, and final messages (the string between '<|message|>' and '<|end|>') in the 'content' field.\") }}"
      "            {%- endif %}"
      "        {%- endif %}"
      "        {%- if \"thinking\" in message %}"
      "            {%- if \"<|channel|>analysis<|message|>\" in message.thinking or \"<|channel|>final<|message|>\" in message.thinking %}"
      "                {{- raise_exception(\"You have passed a message containing <|channel|> tags in the thinking field. Instead of doing this, you should pass analysis messages (the string between '<|message|>' and '<|end|>') in the 'thinking' field, and final messages (the string between '<|message|>' and '<|end|>') in the 'content' field.\") }}"
      "            {%- endif %}"
      "        {%- endif %}"
      "        {%- if \"tool_calls\" in message %}"
      "            {#- We need very careful handling here - we want to drop the tool call analysis message if the model #}"
      "            {#- has output a later <|final|> message, but otherwise we want to retain it. This is the only case #}"
      "            {#- when we render CoT/analysis messages in inference. #}"
      "            {%- set future_final_message = namespace(found=false) %}"
      "            {%- for future_message in loop_messages[loop.index:] %}"
      "                {%- if future_message.role == 'assistant' and \"tool_calls\" not in future_message %}"
      "                    {%- set future_final_message.found = true %}"
      "                {%- endif %}"
      "            {%- endfor %}"
      "            {#- We assume max 1 tool call per message, and so we infer the tool call name #}"
      "            {#- in \"tool\" messages from the most recent assistant tool call name #}"
      "            {%- set tool_call = message.tool_calls[0] %}"
      "            {%- if tool_call.function %}"
      "                {%- set tool_call = tool_call.function %}"
      "            {%- endif %}"
      "            {%- if message.content and message.thinking %}"
      "                {{- raise_exception(\"Cannot pass both content and thinking in an assistant message with tool calls! Put the analysis message in one or the other, but not both.\") }}"
      "            {%- elif message.content and not future_final_message.found %}"
      "                {{- \"<|start|>assistant<|channel|>analysis<|message|>\" + message.content + \"<|end|>\" }}"
      "            {%- elif message.thinking and not future_final_message.found %}"
      "                {{- \"<|start|>assistant<|channel|>analysis<|message|>\" + message.thinking + \"<|end|>\" }}"
      "            {%- endif %}"
      "            {{- \"<|start|>assistant to=\" }}"
      "            {{- \"functions.\" + tool_call.name + \"<|channel|>commentary \" }}"
      "            {{- (tool_call.content_type if tool_call.content_type is defined else \"json\") + \"<|message|>\" }}"
      "            {{- tool_call.arguments|tojson }}"
      "            {{- \"<|call|>\" }}"
      "            {%- set last_tool_call.name = tool_call.name %}"
      "        {%- elif loop.last and not add_generation_prompt %}"
      "            {#- Only render the CoT if the final turn is an assistant turn and add_generation_prompt is false #}"
      "            {#- This is a situation that should only occur in training, never in inference. #}"
      "            {%- if \"thinking\" in message %}"
      "                {{- \"<|start|>assistant<|channel|>analysis<|message|>\" + message.thinking + \"<|end|>\" }}"
      "            {%- endif %}"
      "            {#- <|return|> indicates the end of generation, but <|end|> does not #}"
      "            {#- <|return|> should never be an input to the model, but we include it as the final token #}"
      "            {#- when training, so the model learns to emit it. #}"
      "            {{- \"<|start|>assistant<|channel|>final<|message|>\" + message.content + \"<|return|>\" }}"
      "        {%- else %}"
      "            {#- CoT is dropped during all previous turns, so we never render it for inference #}"
      "            {{- \"<|start|>assistant<|channel|>final<|message|>\" + message.content + \"<|end|>\" }}"
      "            {%- set last_tool_call.name = none %}"
      "        {%- endif %}"
      "    {%- elif message.role == 'tool' -%}"
      "        {%- if last_tool_call.name is none %}"
      "            {{- raise_exception(\"Message has tool role, but there was no previous assistant message with a tool call!\") }}"
      "        {%- endif %}"
      "        {{- \"<|start|>functions.\" + last_tool_call.name }}"
      "        {{- \" to=assistant<|channel|>commentary<|message|>\" + message.content|tojson + \"<|end|>\" }}"
      "    {%- elif message.role == 'user' -%}"
      "        {{- \"<|start|>user<|message|>\" + message.content + \"<|end|>\" }}"
      "    {%- endif -%}"
      "{%- endfor -%}"
      ""
      "{#- Generation prompt #}"
      "{%- if add_generation_prompt -%}"
      "<|start|>assistant<|channel|>final<|message|>"
      "{%- endif -%}"
    )

    _QWEN2 = (
      "{% if not add_generation_prompt is defined %}"
      "    {% set add_generation_prompt = false %}"
      "{% endif %}"
      ""
      "{% set ns = namespace("
      "    is_first=false,"
      "    is_tool=false,"
      "    is_output_first=true,"
      "    system_prompt='',"
      "    is_first_sp=true"
      ") %}"
      ""
      "{# Collect all system messages #}"
      "{%- for message in messages %}"
      "    {%- if message['role'] == 'system' %}"
      "        {%- if ns.is_first_sp %}"
      "            {% set ns.system_prompt = ns.system_prompt + message['content'] %}"
      "            {% set ns.is_first_sp = false %}"
      "        {%- else %}"
      "            {% set ns.system_prompt = ns.system_prompt + '\\n\\n' + message['content'] %}"
      "        {%- endif %}"
      "    {%- endif %}"
      "{%- endfor %}"
      ""
      "{# Output BOS token and system prompt #}"
      "{{ bos_token }}{{ ns.system_prompt }}"
      ""
      "{# Process messages #}"
      "{%- for message in messages %}"
      "    "
      "    {# User message #}"
      "    {%- if message['role'] == 'user' %}"
      "        {%- set ns.is_tool = false -%}"
      "        {{'<｜User｜>' + message['content']}}"
      "    {%- endif %}"
      "    "
      "    {# Assistant message with tool calls #}"
      "    {%- if message['role'] == 'assistant' and 'tool_calls' in message %}"
      "        {%- set ns.is_tool = false -%}"
      "        {%- for tool in message['tool_calls'] %}"
      "            {%- if not ns.is_first %}"
      "                {%- if message['content'] is none %}"
      "                    {{'<｜Assistant｜><｜tool▁calls▁begin｜><｜tool▁call▁begin｜>' + "
      "                      tool['type'] + '<｜tool▁sep｜>' + "
      "                      tool['function']['name'] + '\\n' + "
      "                      '```json' + '\\n' + "
      "                      tool['function']['arguments'] + '\\n' + "
      "                      '```' + '<｜tool▁call▁end｜>'}}"
      "                {%- else %}"
      "                    {{'<｜Assistant｜>' + message['content'] + "
      "                      '<｜tool▁calls▁begin｜><｜tool▁call▁begin｜>' + "
      "                      tool['type'] + '<｜tool▁sep｜>' + "
      "                      tool['function']['name'] + '\\n' + "
      "                      '```json' + '\\n' + "
      "                      tool['function']['arguments'] + '\\n' + "
      "                      '```' + '<｜tool▁call▁end｜>'}}"
      "                {%- endif %}"
      "                {%- set ns.is_first = true -%}"
      "            {%- else %}"
      "                {{'\\n' + '<｜tool▁call▁begin｜>' + "
      "                  tool['type'] + '<｜tool▁sep｜>' + "
      "                  tool['function']['name'] + '\\n' + "
      "                  '```json' + '\\n' + "
      "                  tool['function']['arguments'] + '\\n' + "
      "                  '```' + '<｜tool▁call▁end｜>'}}"
      "            {%- endif %}"
      "        {%- endfor %}"
      "        {{'<｜tool▁calls▁end｜><｜end▁of▁sentence｜>'}}"
      "    {%- endif %}"
      "    "
      "    {# Assistant message without tool calls #}"
      "    {%- if message['role'] == 'assistant' and 'tool_calls' not in message %}"
      "        {%- if ns.is_tool %}"
      "            {{'<｜tool▁outputs▁end｜>' + message['content'] + '<｜end▁of▁sentence｜>'}}"
      "            {%- set ns.is_tool = false -%}"
      "        {%- else %}"
      "            {% set content = message['content'] %}"
      "            {% if '</think>' in content %}"
      "                {% set content = content.split('</think>')[-1] %}"
      "            {% endif %}"
      "            {{'<｜Assistant｜>' + content + '<｜end▁of▁sentence｜>'}}"
      "        {%- endif %}"
      "    {%- endif %}"
      "    "
      "    {# Tool output message #}"
      "    {%- if message['role'] == 'tool' %}"
      "        {%- set ns.is_tool = true -%}"
      "        {%- if ns.is_output_first %}"
      "            {{'<｜tool▁outputs▁begin｜><｜tool▁output▁begin｜>' + "
      "              message['content'] + '<｜tool▁output▁end｜>'}}"
      "            {%- set ns.is_output_first = false %}"
      "        {%- else %}"
      "            {{'<｜tool▁output▁begin｜>' + "
      "              message['content'] + '<｜tool▁output▁end｜>'}}"
      "        {%- endif %}"
      "    {%- endif %}"
      "    "
      "{%- endfor -%}"
      ""
      "{# Close tool outputs if needed #}"
      "{% if ns.is_tool %}"
      "    {{'<｜tool▁outputs▁end｜>'}}"
      "{% endif %}"
      ""
      "{# Add generation prompt if requested #}"
      "{% if add_generation_prompt and not ns.is_tool %}"
      "    {{'<｜Assistant｜>'}}"
      "{% endif %}"
    )

    @classmethod
    def create_chat_template(cls, tmpl_name: str = "default") -> str:
        """Creates and returns a chat template based on the provided name.

        Args:
            tmpl_name (str): The name of the chat template to create.
        Returns:
            str: The chat template string.

        """
        if tmpl_name.lower() == "default":
            return cls._DEFAULT
        elif tmpl_name.lower() == "alpaca":
            return cls._ALPACA
        elif tmpl_name.lower() == "chat_ml":
            return cls._CHAT_ML
        elif tmpl_name.lower() == "falcon":
            return cls._FALCON
        elif tmpl_name.lower() == "gemma":
            return cls._GEMMA
        elif tmpl_name.lower() == "llama_2":
            return cls._LLAMA_2
        elif tmpl_name.lower() == "llama_3":
            return cls._LLAMA_3
        elif tmpl_name.lower() == "mistral":
            return cls._MISTRAL
        elif tmpl_name.lower() == "phi_2":
            return cls._PHI_2
        elif tmpl_name.lower() == "phi_3":
            return cls._PHI_3
        elif tmpl_name.lower() == "qwen":
            return cls._QWEN
        elif tmpl_name.lower() == "openai":
            return cls._GPT_OSS
        elif tmpl_name.lower() == "qwen2":
            return cls._QWEN2
        else:
            raise ValueError("Invalid template name")
