{
 "title": "De-Identification Model",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Number of Processed Docs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(increase(http_requests_total{handler=\"/process\", job=\"cms_de-identification\", method=\"POST\", status=\"2xx\"}[1y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Processed Batches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "round(increase(http_requests_total{handler=\"/process_bulk\", job=\"cms_de-identification\", method=\"POST\", status=\"2xx\"}[1y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"cms_de-identification\", status=\"4xx\"}[$__rate_interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"cms_de-identification\", status=\"5xx\"}[$__rate_interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total Processed Doc Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(http_request_size_bytes_sum{handler=\"/process\", job=\"cms_de-identification\"}[1y])",
     "legendFormat": "/process"
    },
    {
     "expr": "increase(http_request_size_bytes_sum{handler=\"/process_bulk\", job=\"cms_de-identification\"}[1y])",
     "legendFormat": "/process_bulk"
    }
   ]
  },
  {
   "title": "Average Request Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum{job=\"cms_de-identification\"}[1m]) / rate(http_request_size_bytes_count{job=\"cms_de-identification\"}[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{job=\"cms_de-identification\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_de-identification\"}[1m]) / rate(http_request_duration_seconds_count{job=\"cms_de-identification\"}[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{job=\"cms_de-identification\", le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count{job=\"cms_de-identification\"}[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request Size vs Duration (/process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_de-identification\", handler=\"/process\"}[1m]) / rate(http_request_duration_seconds_count{job=\"cms_de-identification\", handler=\"/process\"}[1m])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(http_request_size_bytes_sum{job=\"cms_de-identification\", handler=\"/process\"}[1m]) / rate(http_request_size_bytes_count{job=\"cms_de-identification\", handler=\"/process\"}[1m])",
     "legendFormat": "size"
    },
    {
     "expr": "(rate(http_request_size_bytes_sum{job=\"cms_de-identification\", handler=\"/process\"}[1m]) / rate(http_request_size_bytes_count{job=\"cms_de-identification\", handler=\"/process\"}[1m])) / (rate(http_request_duration_seconds_sum{job=\"cms_de-identification\", handler=\"/process\"}[1m]) / rate(http_request_duration_seconds_count{job=\"cms_de-identification\", handler=\"/process\"}[1m]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Entities vs Duration (/process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_de-identification\", handler=\"/process\"}[1m]) / rate(http_request_duration_seconds_count{job=\"cms_de-identification\", handler=\"/process\"}[1m])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(cms_doc_annotations_sum{job=\"cms_de-identification\", handler=\"/process\"}[1m]) / rate(cms_doc_annotations_count{job=\"cms_de-identification\", handler=\"/process\"}[1m])",
     "legendFormat": "entities"
    },
    {
     "expr": "(rate(cms_doc_annotations_sum{job=\"cms_de-identification\", handler=\"/process\"}[1m]) / rate(cms_doc_annotations_count{job=\"cms_de-identification\", handler=\"/process\"}[1m])) / (rate(http_request_duration_seconds_sum{job=\"cms_de-identification\", handler=\"/process\"}[1m]) / rate(http_request_duration_seconds_count{job=\"cms_de-identification\", handler=\"/process\"}[1m]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Request Size vs Duration (/process_bulk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]) / rate(http_request_duration_seconds_count{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(http_request_size_bytes_sum{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]) / rate(http_request_size_bytes_count{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m])",
     "legendFormat": "size"
    },
    {
     "expr": "(rate(http_request_size_bytes_sum{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]) / rate(http_request_size_bytes_count{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m])) / (rate(http_request_duration_seconds_sum{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]) / rate(http_request_duration_seconds_count{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Entities vs Duration (/process_bulk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]) / rate(http_request_duration_seconds_count{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(cms_doc_annotations_sum{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]) / rate(cms_doc_annotations_count{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m])",
     "legendFormat": "entities"
    },
    {
     "expr": "(rate(cms_doc_annotations_sum{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]) / rate(cms_doc_annotations_count{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m])) / (rate(http_request_duration_seconds_sum{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]) / rate(http_request_duration_seconds_count{job=\"cms_de-identification\", handler=\"/process_bulk\"}[1m]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Request Duration (P50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=\"cms_de-identification\", handler!=\"none\"}[$__rate_interval]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request Duration (P90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{job=\"cms_de-identification\", handler!=\"none\"}[1m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"cms_de-identification\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"cms_de-identification\"}[$__rate_interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"cms_de-identification\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}