{
 "title": "De-Identification MedCAT Model",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Number of Processed Docs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(increase(http_requests_total{handler=\"/process\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", method=\"POST\", status=\"2xx\"}[10y]))",
     "legendFormat": "/process"
    },
    {
     "expr": "round(increase(http_requests_total{handler=\"/redact\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", method=\"POST\", status=\"2xx\"}[10y]))",
     "legendFormat": "/redact"
    },
    {
     "expr": "round(increase(http_requests_total{handler=\"/process_bulk\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", method=\"POST\", status=\"2xx\"}[10y]))",
     "legendFormat": "/process_bulk"
    }
   ]
  },
  {
   "title": "Number of Processed Batches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "round(increase(http_requests_total{handler=\"/process_bulk\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", method=\"POST\", status=\"2xx\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", status=\"4xx\"}[$__rate_interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", status=\"5xx\"}[$__rate_interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Number of Recognised Entities ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(cms_doc_annotations_sum{handler=\"/process\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}[10y]))",
     "legendFormat": "/process"
    },
    {
     "expr": "round(increase(cms_doc_annotations_sum{handler=\"/process_bulk\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}[10y]))",
     "legendFormat": "/process_bulk"
    },
    {
     "expr": "round(increase(cms_doc_annotations_sum{handler=\"/redact\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}[10y]))",
     "legendFormat": "/redact"
    }
   ]
  },
  {
   "title": "Processed Doc Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(http_request_size_bytes_sum{handler=\"/process\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}[10y])",
     "legendFormat": "/process"
    },
    {
     "expr": "increase(http_request_size_bytes_sum{handler=\"/process_bulk\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}[10y])",
     "legendFormat": "/process_bulk"
    },
    {
     "expr": "increase(http_request_size_bytes_sum{handler=\"/redact\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}[10y])",
     "legendFormat": "/redact"
    }
   ]
  },
  {
   "title": "Average Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler!=\"/favicon.ico\"}[$__rate_interval]) / rate(http_request_size_bytes_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler!=\"/favicon.ico\"}[$__rate_interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}[$__rate_interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler!=\"/favicon.ico\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler!=\"/favicon.ico\"}[$__rate_interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 500ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler!=\"/favicon.ico\", le=\"0.5\"}[$__rate_interval]) \n/ ignoring (le) increase(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler!=\"/favicon.ico\"}[$__rate_interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request Size vs Duration (/process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(http_request_size_bytes_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]) / rate(http_request_size_bytes_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval])",
     "legendFormat": "size"
    },
    {
     "expr": "(rate(http_request_size_bytes_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]) / on(job, instance, handler) rate(http_request_size_bytes_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval])) / (rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]) / on(job, instance, handler) rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Recognised Entities vs Duration (/process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(cms_doc_annotations_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]) / rate(cms_doc_annotations_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval])",
     "legendFormat": "entities"
    },
    {
     "expr": "(rate(cms_doc_annotations_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]) / on(job, instance, handler) rate(cms_doc_annotations_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval])) / (rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]) / on(job, instance, handler) rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process\"}[$__rate_interval]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Request Size vs Duration (/redact)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(http_request_size_bytes_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]) / rate(http_request_size_bytes_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval])",
     "legendFormat": "size"
    },
    {
     "expr": "(rate(http_request_size_bytes_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]) / on(job, instance, handler) rate(http_request_size_bytes_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval])) / (rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]) / on(job, instance, handler) rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Recognised Entities vs Duration (/redact)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(cms_doc_annotations_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]) / rate(cms_doc_annotations_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval])",
     "legendFormat": "entities"
    },
    {
     "expr": "(rate(cms_doc_annotations_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]) / on(job, instance, handler) rate(cms_doc_annotations_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval])) / (rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]) / on(job, instance, handler) rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/redact\"}[$__rate_interval]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Request Size vs Duration (/process_bulk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(http_request_size_bytes_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]) / rate(http_request_size_bytes_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval])",
     "legendFormat": "size"
    },
    {
     "expr": "(rate(http_request_size_bytes_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]) / on(job, instance, handler) rate(http_request_size_bytes_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval])) / (rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]) / on(job, instance, handler) rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Recognised Entities vs Duration (/process_bulk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval])",
     "legendFormat": "duration"
    },
    {
     "expr": "rate(cms_doc_annotations_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]) / rate(cms_doc_annotations_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval])",
     "legendFormat": "entities"
    },
    {
     "expr": "(rate(cms_doc_annotations_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]) / on(job, instance, handler) rate(cms_doc_annotations_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval])) / (rate(http_request_duration_seconds_sum{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]) / on(job, instance, handler) rate(http_request_duration_seconds_count{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler=\"/process_bulk\"}[$__rate_interval]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Average Accuracies of Recognised Entities per Concept",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cms_avg_anno_acc_per_concept{handler=\"/redact\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}",
     "legendFormat": "{{concept}}"
    },
    {
     "expr": "cms_avg_anno_acc_per_concept{handler=\"/process\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}",
     "legendFormat": "{{concept}}"
    },
    {
     "expr": "cms_avg_anno_acc_per_concept{handler=\"/process_bulk\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}",
     "legendFormat": "{{concept}}"
    }
   ]
  },
  {
   "title": "Average Accuracies of Recognised Entities per Doc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cms_avg_anno_acc_per_doc{handler=\"/redact\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}",
     "legendFormat": "/redact"
    },
    {
     "expr": "cms_avg_anno_acc_per_doc{handler=\"/process\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}",
     "legendFormat": "/process"
    },
    {
     "expr": "cms_avg_anno_acc_per_doc{handler=\"/process_bulk\", job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}",
     "legendFormat": "/process_bulk"
    }
   ]
  },
  {
   "title": "Request Duration (P50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler!~\"none|/favicon.ico\"}[$__rate_interval]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request Duration (P90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\", handler!~\"none|/favicon.ico\"}[$__rate_interval]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}[$__rate_interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 74 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"cms_medcat-deid\", instance=\"medcat-deid:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}