{
 "title": "UMLS MedCAT Model",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Duration on /process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(cms_request_duration_seconds_sum{app_name=\"UMLS MedCAT model\", path=\"/process\"}[5m]) / rate(cms_request_duration_seconds_count{app_name=\"UMLS MedCAT model\", path=\"/process\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration on /process_bulk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(cms_request_duration_seconds_sum{app_name=\"UMLS MedCAT model\", path=\"/process_bulk\"}[5m]) / rate(cms_request_duration_seconds_count{app_name=\"UMLS MedCAT model\", path=\"/process_bulk\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Body Bytes on /process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(cms_request_body_bytes_total{app_name=\"UMLS MedCAT model\", path=\"/process\"}[5m]) / rate(cms_request_duration_seconds_count{app_name=\"UMLS MedCAT model\", path=\"/process\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Body Bytes on /process_bulk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(cms_request_body_bytes_total{app_name=\"UMLS MedCAT model\", path=\"/process_bulk\"}[5m]) / rate(cms_request_duration_seconds_count{app_name=\"UMLS MedCAT model\", path=\"/process_bulk\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Body Bytes on /process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(cms_response_body_bytes_total{app_name=\"UMLS MedCAT model\", path=\"/process\"}[5m]) / rate(cms_request_duration_seconds_count{app_name=\"UMLS MedCAT model\", path=\"/process\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Body Bytes on /process_bulk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(cms_response_body_bytes_total{app_name=\"UMLS MedCAT model\", path=\"/process_bulk\"}[5m]) / rate(cms_request_duration_seconds_count{app_name=\"UMLS MedCAT model\", path=\"/process_bulk\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration on /train_unsupervised",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(cms_request_duration_seconds_sum{app_name=\"UMLS MedCAT model\", path=\"/train_unsupervised\"}[5m]) / rate(cms_request_duration_seconds_count{app_name=\"UMLS MedCAT model\", path=\"/train_unsupervised\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration on /train_supervised",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(cms_request_duration_seconds_sum{app_name=\"UMLS MedCAT model\", path=\"/train_supervised\"}[5m]) / rate(cms_request_duration_seconds_count{app_name=\"UMLS MedCAT model\", path=\"/train_supervised\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration on /info",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(cms_request_duration_seconds_sum{app_name=\"UMLS MedCAT model\", path=\"/info\"}[5m]) / rate(cms_request_duration_seconds_count{app_name=\"UMLS MedCAT model\", path=\"/info\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}