name: api-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    if: |
      github.repository == 'CogStack/CogStack-ModelServe' &&
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Generate OpenAPI docs
        run: |
          python app/cli/cli.py export-model-apis --model-type medcat_snomed --add-training-apis --no-exclude-unsupervised-training --no-exclude-metacat-training --add-evaluation-apis --add-previews-apis
          python app/cli/cli.py export-model-apis --model-type medcat_icd10 --add-training-apis --no-exclude-unsupervised-training --no-exclude-metacat-training --add-evaluation-apis --add-previews-apis
          python app/cli/cli.py export-model-apis --model-type medcat_opcs4 --add-training-apis --no-exclude-unsupervised-training --no-exclude-metacat-training --add-evaluation-apis --add-previews-apis
          python app/cli/cli.py export-model-apis --model-type medcat_umls --add-training-apis --no-exclude-unsupervised-training --no-exclude-metacat-training --add-evaluation-apis --add-previews-apis
          python app/cli/cli.py export-model-apis --model-type anoncat --add-training-apis --add-evaluation-apis --add-previews-apis --exclude-metacat-training --exclude-unsupervised-training
          python app/cli/cli.py export-model-apis --model-type transformers_deid --add-training-apis --add-evaluation-apis --add-previews-apis --exclude-metacat-training --exclude-unsupervised-training
          python app/cli/cli.py export-model-apis --model-type huggingface_ner --add-training-apis --add-evaluation-apis --add-previews-apis --exclude-metacat-training
          python app/cli/cli.py export-model-apis --model-type huggingface_llm
          python app/cli/cli.py export-openapi-spec
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          mv ./medcat_snomed_model_apis.json ./docs/medcat_snomed_model_apis.json
          mv ./medcat_icd10_model_apis.json ./docs/medcat_icd10_model_apis.json
          mv ./medcat_opcs4_model_apis.json ./docs/medcat_opcs4_model_apis.json
          mv ./medcat_umls_model_apis.json ./docs/medcat_umls_model_apis.json
          mv ./anoncat_model_apis.json ./docs/anoncat_model_apis.json
          mv ./transformers_deid_model_apis.json ./docs/transformers_deid_model_apis.json
          mv ./huggingface_ner_model_apis.json ./docs/huggingface_ner_model_apis.json
          mv ./huggingface_llm_model_apis.json ./docs/huggingface_llm_model_apis.json
          mv ./cogstack_model_serve_apis.json ./docs/cogstack_model_serve_apis.json
          git config --global user.name "cogstack-model-serve"
          git config --global user.email "cogstack-model-serve@users.noreply.github.com"
          git add ./docs/medcat_snomed_model_apis.json ./docs/medcat_icd10_model_apis.json ./docs/medcat_opcs4_model_apis.json ./docs/medcat_umls_model_apis.json ./docs/anoncat_model_apis.json ./docs/transformers_deid_model_apis.json ./docs/huggingface_ner_model_apis.json ./docs/huggingface_llm_model_apis.json ./docs/cogstack_model_serve_apis.json
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            git commit -m "update api docs"
          else
            echo "No OpenAPI doc changes detected and publishing skipped."
            exit 0
          fi
      - name: Update OpenAPI docs
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
