name: docker extra

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'docker/mlflow/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker/mlflow/**'

env:
  REGISTRY: docker.io
  DOCKER_IMAGE_NAME: cogstacksystems/cogstack-mlflow-ui

jobs:
  lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: hadolint --ignore DL3008 --ignore DL3013 --ignore DL3003 --ignore DL4006 docker/mlflow/**/Dockerfile*

  build-and-push:
    needs: lint
    if: |
      github.repository == 'CogStack/CogStack-ModelServe' &&
      (
        github.ref == 'refs/heads/main' ||
        github.event_name == 'pull_request' ||
        github.event_name == 'workflow_dispatch'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    concurrency: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Extract MLflow UI meta
        id: cms_mlflow_ui_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
            type=match,pattern=cogstack-modelserve/v(\d+\.\d+\.\d+),group=1

      - name: Build and push MLflow UI
        uses: docker/build-push-action@v6
        id: build_and_push_mlflow_ui
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: docker/mlflow/server/Dockerfile
          push: true
          tags: ${{ steps.cms_mlflow_ui_meta.outputs.tags }}
          labels: ${{ steps.cms_mlflow_ui_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      
      - name: Attest image artifacts
        uses: actions/attest-build-provenance@v2
        id: attest
        with:
            subject-name: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
            subject-digest: ${{ steps.build_and_push_mlflow_ui.outputs.digest }}
            push-to-registry: true

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          readme-filepath: ./docker/mlflow/server/README.md
