name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
      max-parallel: 2

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Check types
        run: |
          python -m mypy --follow-imports=normal app/model_services/*.py app/management/*.py app/processors/*.py app/api/*.py app/api/routers/*.py app/api/auth/*.py app/cli/*.py app/trainers/*.py app/*.py
      - name: Lint
        uses: astral-sh/ruff-action@v1
      - name: Test
        run: |
          pytest --cov --cov-report=html:coverage_reports #--random-order 
