name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt -r app/requirements-dev.txt
      - name: Check types
        run: |
          python -m mypy --follow-imports=normal app/model_services/*.py app/management/*.py app/processors/*.py app/routers/*.py app/*.py
      - name: Lint
        run: |
          flake8 app/model_services/*.py app/management/*.py app/processors app/routers/*.py app/*.py
      - name: Test
        run: |
          pytest -s -vv tests